---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: default
nameSuffix: -dev

images:
- name: jmanzur/hello-app:latest
  newName: jmanzur/hello-app:1
  newTag: 1


configMapGenerator:
- literals:
  - TARGET=JManzur
  name: hello-app-cm

labels:
- includeSelectors: true
  pairs:
    app: hello-app
    component: hello-app